- name: Check if local kubeconfig file exists
  local_action:
    module: stat
    path: "{{ kubeconfig_path }}"
  become: false
  register: kubeconfig_local

- name: Generate Kubeconfig file
  block:
    - name: Retrieve kubeconfig file
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: "{{ kubeconfig_path }}"
        flat: yes

    - name: Update kubeconfig server address
      local_action:
        module: lineinfile
        path: "{{ kubeconfig_path }}"
        regexp: '^    server: .*'
        line: '    server: https://{{ hostvars["host"].ansible_host }}:6443'
      become: false
  when: kubeconfig_local.stat.exists == False
