---
- name: Ensure {{ device_path }} is partitioned
  parted:
    device: "{{ device_path }}"
    number: 1
    state: present
    part_type: primary

- name: Create physical volume on {{ device_path }}1
  community.general.lvg:
    vg: vg_data
    pvs: "{{ device_path }}1"
    pesize: "{{ device_size }}"

- name: Check if logical volume lv_data exists
  command: lvdisplay /dev/vg_data/lv_data
  register: lv_data_check
  ignore_errors: yes

- name: Create a logical volume on {{ device_path }}1
  community.general.lvol:
    vg: vg_data
    lv: lv_data
    size: +100%FREE
  when: lv_data_check.rc != 0

- name: Format the logical volume with ext4
  filesystem:
    fstype: ext4
    dev: /dev/vg_data/lv_data

- name: Create mount point
  file:
    path: /mnt/data
    state: directory

- name: Mount the logical volume
  mount:
    path: /mnt/data
    src: /dev/vg_data/lv_data
    fstype: ext4
    state: mounted

- name: Ensure the logical volume is mounted on boot
  mount:
    path: /mnt/data
    src: /dev/vg_data/lv_data
    fstype: ext4
    opts: defaults
    state: present
