ingress_install: true
ingress_name: "ingress-nginx"
ingress_class_name: "nginx"
ingress_helm_repo_name: "ingress-nginx"
ingress_helm_repo_url: "https://kubernetes.github.io/ingress-nginx"
ingress_helm_version: "4.11.1"
ingress_namespace: "ingress-nginx"
ingress_node_port_http: 30080
ingress_node_port_https: 30443
